config:
  plugins:
    metrics-by-endpoint: {}
  target: "http://127.0.0.1:8080"
  phases:
    - duration: 20
      arrivalRate: 10

scenarios:
  - name: 'Sessions flow (register + login)'
    flow:
      - log: 'Creamos un usuario de prueba'
      - get:
          url: /pruebas/testuser
          capture:
            - json: "$.first_name"
              as: "first_name"
            - json: "$.last_name"
              as: "last_name"
            - json: "$.email"
              as: "email"
            - json: "$.password"
              as: "password"
      - log: 'Register de user'
      - post:
          url: 'sessions/register'
          json:
            first_name: "{{first_name}}"
            last_name: "{{last_name}}"
            email: "{{email}}"
            password: "{{password}}"
      - log: 'Login de user'
      - post:
          url: 'sessions/login'
          json:
            email: "{{email}}"
            password: "{{password}}"
